### PR TITLE
Issue #29 improve typing for precision keyword

### PR DESCRIPTION
**Pull request by Saber-Bjeoui**
Hello,
I added typedef for precision keyword, ready for code review.
Happy to hear any feedbacks.

### CODE REVIEW

**Comment by meduzen** [comment]
Looks good, thanks! I’m gonna review it soon.

For your information, your PR contains modification of the NPM lock file (using v1 instead of v2: more about it on the [official doc](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#handling-old-lockfiles)). If you know how to do revert it, feel free to do it. Otherwise I’ll do it later on.

Also the TypeScript definitions have to be updated. It’s half-automatized, but I should document it.

**Comment by Saber-Bjeoui** [comment]
Cool, I think package-lock is ok now I was using npm 6 that's why it result in the lockfileVersion being 1 (the resource you gave was helpful).

Also Typescript definition files are added. I have a question though about the test-types specifically these two:
* ``` expectType<string>(datetime(date, 'n00t')) ``` line 28
* ``` expectType<string>(utc(date, 'n00t')) ``` line 34
of course above two test fails but what they are supposing to test here?

**Comment by meduzen** [comment]
Finally answering!

## The tests

> Also Typescript definition files are added. I have a question though about the test-types specifically these two:
> 
>     * `expectType<string>(datetime(date, 'n00t'))` line 28
> 
>     * `expectType<string>(utc(date, 'n00t'))` line 34
> 
> 
> of course above two test fails but what they are supposed to test here?

Before this PR, `datetime` and `utc` was typed to accept any string as precision, which reflects how the function works: you can give any _unsupported_ string to `datetime`, and it falls back on `day`. (Actually, even other types than string falls to `day`.)

I agree these tests were a bit useless or premature (in a sense that I wrote them in prevision to restrict the types like this PR does).

So, now that both tests are failing, it means:
- the types changes done in this PR are correct: _unsupported_ precision keywords aren’t allowed anymore;
- these two tests can be replaced by [`expectError`](https://github.com/SamVerschueren/tsd#expecterrortvalue) (which is [weirdly documented](https://github.com/SamVerschueren/tsd/issues/55#issuecomment-616235426)) instead of `expectType`.

I think the way most [`tsd`](https://github.com/SamVerschueren/tsd#expecterrortvalue) `expectSomething` functions works is that they crash if the parameters types don’t match the declaration.

## The types

1. `precisionKeyword` can be renamed `Precision`, with a capital `P`: I think there’s a consensus on capitalizing types (and leave the lowercase to JS primitives like `string`, `boolean`…). What do you think, @Saber-Bjeoui?

2. `utc()` works with a limited number of precisions: (default) `datetime`, `datetime ms`, `time`, `ms`. So this means the type you propose is a bit too broad for it.

I was thinking about splitting the new type in two, and then use a combined type where needed, but this is overcomplicated.  Maybe this for `utc` could do the trick for `utc`:
```js
@param {'datetime'|'datetime ms'|'time'|'ms'} precision
```

What do you think?

**Comment by Saber-Bjeoui** [comment]
> 1. precisionKeyword can be renamed Precision, with a capital P: I think there’s a consensus on capitalizing types (and leave the lowercase to JS primitives like string, boolean…). What do you think, @Saber-Bjeoui?

I agree with capitalizing types, that's goes along with Typescript documentation.

>    2.utc() works with a limited number of precisions: (default) datetime, datetime ms, time, ms. So this means the type you propose is a bit too broad for it.
>
>I was thinking about splitting the new type in two, and then use a combined type where needed, but this is overcomplicated. Maybe this for utc could do the trick for UTC:
>
>@param {'datetime'|'datetime ms'|'time'|'ms'} precision
>
>What do you think?

So the utc() function will have precision param with type like so:

@param {'datetime'|'datetime second'|'datetime ms'|'time'|'second'|'ms'} precision

is this correct? if it's correct then no need to overcomplcate thinks, unless the type declared above will be reused else where.

**Comment by meduzen** [comment]
You’re right for `utc()`! I forgot `datetime second` and `second` in my message. 😐

So it’s indeed:
`@param {'datetime' | 'datetime second' | 'datetime ms' | 'time' | 'second' | 'ms'} precision`

And it won’t be re-used anywhere else.

**Comment by Saber-Bjeoui** [comment]
Hello,
Thank you for your answer, I had a problem on my laptop and I couldn't do much (had to install github on my old phone to answer here).

 I got my laptop fixed this day.I will make sure to push the changes asap.

**Comment by meduzen** [comment]
Many thanks, @Saber-Bjeoui! I was about to write you a message to ask if you wanted to continue the PR or not. I hope everything is fine on your side of the sea. Take the time you need. :)

**Review by meduzen — APPROVED** [review]

**Comment by meduzen** [comment]
It’s published in [1.2](https://github.com/meduzen/datetime-attribute/releases/tag/1.2.0). 🎉 

[Appreciation tweet](https://twitter.com/meduzen/status/1501706103247323142). 🤝

**Pull request merged**
